name = "Facebook Pixel Minimal"
type = "web_pixel_extension"

runtime_context = "strict"

[settings]
type = "object"

[settings.fields.accountID]
name = "Facebook Pixel ID"
description = "Enter your Facebook Pixel ID"
type = "single_line_text_field"
validations = [
  { name = "min", value = "1" }
]
