type = "web_pixel"
name = "Facebook Pixel Gateway Final"

runtime_context = "strict"

[settings]
type = "object"

[settings.fields.pixelId]
name = "Facebook Pixel ID"
description = "Your Facebook Pixel ID"
type = "single_line_text_field"
validations = [
  { name = "min", value = "1" }
]

[settings.fields.debug]
name = "Debug Mode"
description = "Enable debug logging"
type = "boolean"
default = true
